AWSTemplateFormatVersion: 2010-09-09
Description: Peter Ocansey | Basic IaC VPC Challenge - This template deploys an Infrastracture As Code

Parameters:
    
    EnvironmentName:
      Description: An environment name that will be prefixed to resources
      Type: String

    AMItoUse:
      Description: AMI to use for our base image
      Type: String

Resources:

    RoleForSSMAccess: 
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - ec2.amazonaws.com
              Action:
                - 'sts:AssumeRole'
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

    ServerInstanceProfile: 
      Type: "AWS::IAM::InstanceProfile"
      Properties: 
        Roles: 
          - !Ref RoleForSSMAccess
    

    WebServerSecGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Allow http to our hosts
        VpcId:
          Fn::ImportValue:
            !Sub "${EnvironmentName}-VPCID"
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0

    ServerInstance: 
      Type: AWS::EC2::Instance
      Properties:
        InstanceType: t3.micro
        ImageId: !Ref AMItoUse
        IamInstanceProfile: !Ref ServerInstanceProfile
        NetworkInterfaces: 
          - AssociatePublicIpAddress: "true"
            DeviceIndex: "0"
            GroupSet: 
              - Ref: "WebServerSecGroup"
            SubnetId:
              Fn::ImportValue: 
                !Sub "${EnvironmentName}-PRI-SN"